# Stuffs the python

Dada un vector comvertirlo en un vector columna

In [2]:
import numpy as np

# arr = np.array([i for i in range(10)])
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
vec_colum = arr.reshape(-1, 1)
vec_colum

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [4]:
arr.reshape(1, -1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

Concaterar dos vectores columas para convertirla aun array 2-d

In [8]:
np.hstack( (vec_colum, vec_colum) )

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

Concatenar hacia abajo:

In [9]:
np.vstack( (vec_colum, vec_colum) )

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

Dada una matrix, convertirla en un vector:

In [5]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

In [6]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])